AIUnits = {
    ElvenArcher : {
        type: "ai_monster",
        Name: "ElvenArcher",
        Cost: 15,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 32,
        height: 32,
        xOffset: 0,
        yOffset: 20,
        hp: 20,
        attack: 5
    },
    DwarvenKnight : {
        type: "ai_monster",
        Name: "DwarvenKnight",
        Cost: 25,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 32,
        height: 32,
        xOffset: 0,
        yOffset: 20,
        hp: 40,
        attack: 15
    },
    Cannoneer : {
        type: "ai_monster",
        Name: "Cannoneer",
        Cost: 40,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 32,
        height: 32,
        xOffset: 0,
        yOffset: -12,
        hp: 50,
        attack: 20
    },
    BlazitMage : {
        type: "ai_monster",
        Name: "BlazitMage",
        Cost: 20,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 32,
        height: 32,
        xOffset: 0,
        yOffset: -12,
        hp: 30,
        attack: 15
    },
    TimberMech : {
        type: "ai_monster",
        Name: "TimberMech",
        Cost: 80,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Slow,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 64,
        height: 64,
        xOffset: 0,
        yOffset: 0,
        hp: 80,
        attack: 30
    }
    
};