AIUnits = {
    ElvenArcher : {
        type: "ai_monster",
        Name: "ElvenArcher",
        Cost: 15,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 81,
        height: 81,
        xOffset: 0,
        yOffset: 0,
        hp: 1,//20,
        attack: 2,
        attackRange: 300
    },
    DwarvenKnight : {
        type: "ai_monster",
        Name: "DwarvenKnight",
        Cost: 25,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 81,
        height: 81,
        xOffset: 0,
        yOffset: 0,
        hp: 1,//40,
        attack: 15,
        attackRange: 30
    },
    Cannoneer : {
        type: "ai_monster",
        Name: "Cannoneer",
        Cost: 40,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 161,
        height: 161,
        xOffset: 0,
        yOffset: -12,
        hp: 1,//50,
        attack: 20,
        attackRange: 30
    },
    BlazitMage : {
        type: "ai_monster",
        Name: "BlazitMage",
        Cost: 20,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Medium,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 151,
        height: 151,
        xOffset: 0,
        yOffset: -12,
        hp: 30,
        attack: 15,
        attackRange: 130
    },
    TimberMech : {
        type: "ai_monster",
        Name: "TimberMech",
        Cost: 80,
        Size: GameTypes.Sizes.Large,
        Faction: GameTypes.Faction.Enemy,
        MovementSpeed: GameTypes.Speeds.Slow,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Ranged],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 301,
        height: 301,
        xOffset: 0,
        yOffset: 10,
        hp: 1,//80,
        attack: 30,
        attackRange: 128
    }
    
};