PlayerUnits = {
    KoboldRunner : {
        Name: "KoboldRunner",
        Cost: 10,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Player,
        MovementSpeed: GameTypes.Speeds.Fast,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Melee],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 81,
        height: 81
    },
    KoboldSap : {
        Name: "KoboldSap",
        Cost: 10,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Player,
        MovementSpeed: GameTypes.Speeds.Fast,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Melee],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 81,
        height: 81
    },
    Goblin : {
        Name: "Goblin",
        Cost: 10,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Player,
        MovementSpeed: GameTypes.Speeds.Fast,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Melee],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 81,
        height: 81
    },
    OrcSpearThrower : {
        Name: "OrcSpearThrower",
        Cost: 10,
        Size: GameTypes.Sizes.Small,
        Faction: GameTypes.Faction.Player,
        MovementSpeed: GameTypes.Speeds.Fast,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Melee],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 81,
        height: 81
    },
    MossGolem : {
        Name: "MossGolem",
        Cost: 10,
        Size: GameTypes.Sizes.Medium,
        Faction: GameTypes.Faction.Player,
        MovementSpeed: GameTypes.Speeds.Fast,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Melee],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 201,
        height: 201
    },
    RockQuarry : {
        Name: "RockQuarry",
        Cost: 10,
        Size: GameTypes.Sizes.Large,
        Faction: GameTypes.Faction.Player,
        MovementSpeed: GameTypes.Speeds.Fast,
        AttackSpeed: GameTypes.Speeds.Medium,
        ArmorTypes: GameTypes.ArmorTypes.Light,
        AttackTypes: [GameTypes.AttackTypes.Melee],
        AdvantageTo: [],
        DisadvantageTo: [],
        width: 201,
        height: 201
    }
};